services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.devEnv
    init: true
    stdin_open: true
    tty: true
    volumes:
      - ../:/app:delegated # Source code mounting
      - volume-pnpm-store:/app/.pnpm-store # Package cache persistence
      - volume-convex-auth:/root/.convex
      - ~/.local/share/opencode:/root/.local/share/opencode # https://opencode.ai/docs/providers/#credentials
      - ~/.config/opencode:/root/.config/opencode # https://opencode.ai/docs/config/#global
      - ~/.claude:/root/.claude # Claude Code cache persistence
      - ~/.claude.json:/root/.claude.json # Claude Code cache persistence
      - ~/.codex:/root/.codex # OpenAI cache persistence
      - ~/.alchemy:/root/.alchemy

    working_dir: /app
    ports:
      - "3000:3000"
      - "3001:3001" # Convex dev server
    env_file:
      - ../.env
      - ../.env.local
      - ../.env.development
    command: pnpm dev
  #   depends_on:
  #     - convex

  # # Local Convex Backend
  # convex:
  #   image: ghcr.io/get-convex/convex-backend:latest
  #   volumes:
  #     - volume-convex-data:/convex/data       # Persist Convex local data
  #   ports:
  #     - "3210:3210"  # Convex backend API
  #     - "3211:3211"  # Convex HTTP actions
  #     - "6791:6791"  # Convex dashboard (optional)
  #   environment:
  #     - CONVEX_INSTANCE_NAME=convex-local-dev
  #     - CONVEX_INSTANCE_SECRET=4361726e69746572616c6c79206d65616e696e6720226c6974
  #   profiles:
  #     - local

  # convex-dashboard:
  #   image: ghcr.io/get-convex/convex-dashboard:latest
  #   stop_grace_period: 10s
  #   stop_signal: SIGINT
  #   ports:
  #     - "${DASHBOARD_PORT:-6791}:6791"
  #   environment:
  #     - NEXT_PUBLIC_DEPLOYMENT_URL=${NEXT_PUBLIC_DEPLOYMENT_URL:-http://127.0.0.1:${PORT:-3210}}
  #   depends_on:
  #     backend:
  #       condition: service_healthy

volumes:
  volume-pnpm-store: # Persist package manager cache
  volume-convex-auth: # Persist Convex authentication
  # volume-convex-data:     # Persist local Convex data
